<h2> Adicionar produto </h2>
<form action="" method="post">
  <div class="mb-3">
    <label for="id_desc" class=""> Descrição </label>
    <input type="text" class="form-control" id="id_desc" name="descricao" placeholder="" required>
  </div>
  <div class="mb-3">
    <label for="id_valor" class=""> Valor </label>
    <input type="decimal" class="form-control" id="id_valor" name="valor" placeholder="" required>
  </div>
  <button class="btn btn-dark" type="submit"> Adicionar </button>
</form>
<?php
  if (isset($_POST['descricao']) && isset($_POST['valor']) && !empty($_POST['descricao']) && !empty($_POST['valor'])){
    
    $query = "INSERT INTO tb_produtos (descricao, valor) VALUES ('{$_POST['descricao']}', '{$_POST['valor']}')";

    $con = Conexao::open();

    mysqli_query($con, $query);

  }
?>