<h1>Lista de produtos</h1>

<nav class="mb-3">
    <a class="btn btn-dark" href="/produtos/adicionar" role="button"> + Add produto </a>
</nav>

<?php
    /*$produtos = [
        [
            'descricao' => 'Pizza',
            'valor' => 23.90,
        ],
        [
            'descricao' => 'Filé Mignon',
            'valor' => 54.90,
        ],
        [
            'descricao' => 'Pepsi Twist',
            'valor' => 6.99,
        ],
    ];*/

    $con = Conexao::open();
    $query = "SELECT * FROM tb_produtos";
    $resultado = mysqli_query($con, $query);
    $result = mysqli_fetch_all($resultado);
?> 

<table class="table table-striped table-hover mt-3">
    <thead class="table-dark">
        <tr>
            <th>Descrição</th>
            <th>Valor</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            /*foreach ($produtos as $cada) {
                echo "<tr>
                    <td>{$cada['descricao']}</td>
                    <td>{$cada['valor']}</td>
                    <td>  </td>
                </tr>";
            }*/
            for($i=0; $i<count($result); $i++){
                echo "<tr>
                    <td>{$result[$i][1]}</td>
                    <td>{$result[$i][2]}</td>
                    <td>  </td>
                </tr>";
            }
        ?>
    </tbody>
</table>